"""Build a runnable harness out of an imported call log.

Given the log and the steps the user agreed to move, this writes a `harness.py` + `tasks.jsonl` that
**replays** their pipeline: each logged step runs again in its logged order, generation steps with the
original prompt, accepted decision steps as a typed decision. The baseline arm re-runs the user's own
logged prompt (via `legacy=`), so the comparison is against their real code path, not our paraphrase.

What a replay can and cannot show
---------------------------------
It measures, on their own traffic: whether the decision model reproduces their decisions, how much
latency and how many tokens each step costs, and what the whole pipeline costs per task.

It cannot show downstream effects. The logged prompts are fixed, so a different routing decision does
not change what the next step sees. For that, the harness has to be written for real (docs/HARNESS.md);
the replay is the cheap screen that says whether it is worth doing.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from pprint import pformat
from typing import Any

from .trace import RawCall, SiteAnalysis, TraceReport

HARNESS = '''"""Replay harness generated by JevControl from {source}.

Do not hand-edit: rebuild it from the Import page (or `jevcontrol.core.imported.build`) instead.

Each task is one task from the log. Its steps run in the logged order:
  * generation steps re-send the original prompt to the main LLM;
  * moved steps become a typed decision ({moved});
  * the baseline arm answers those with the ORIGINAL logged prompt (legacy=), so it reproduces the
    pipeline as it runs today.

`score` is pipeline FIDELITY, not accuracy: the fraction of moved decisions that came out the same as in
the log. The log is the reference, so the baseline arm should score near 1.0; a candidate below that is
changing decisions. Nothing here knows whether the logged answers were right.
"""

META = {meta}

SITES = {sites}


def run(task, ctx):
    answers = {{}}
    for step in task["steps"]:
        site, key = step["site"], step["key"]
        spec = SITES.get(site) or {{"kind": "generation", "max_tokens": 256}}
        kind = spec["kind"]
        if kind == "generation":
            answers[key] = ctx.llm.chat(step["messages"], max_tokens=spec["max_tokens"], site=site)
            continue
        # The original call, used verbatim by the baseline arm.
        def legacy(llm, messages=step["messages"], cap=spec["max_tokens"]):
            return llm.chat(messages, max_tokens=cap)

        if kind == "noul":
            d = ctx.decide.noul(site, step["state"], spec["instructions"], key=key, legacy=legacy)
        elif kind == "score":
            d = ctx.decide.score(site, step["state"], spec["instructions"], spec["options"], key=key, legacy=legacy)
        else:
            d = ctx.decide.choice(site, step["state"], spec["instructions"], spec["options"], key=key, legacy=legacy)
        answers[key] = d.selected
    return answers


def score(task, out):
    """Fidelity: of the moved decisions in this task, how many match the logged answer."""
    graded = [(s["key"], s["logged"]) for s in task["steps"]
              if (SITES.get(s["site"]) or {{}}).get("kind", "generation") != "generation"]
    if not graded:
        return 1.0
    hit = sum(1 for key, logged in graded if str(out.get(key, "")).strip().lower() == str(logged).strip().lower())
    return hit / len(graded)
'''


MAX_STATE_CHARS = 12_000


def _state_of(call: RawCall, site: SiteAnalysis) -> str:
    """The part of the prompt that varies at this step, with its field label kept.

    The fixed template is stripped, since the question carries it. But the template's last line is usually the
    label of the varying value ("Customer message:", "Ticket:"), and without it the state can be a bare value
    with nothing to say what it is - so that line is kept.
    """
    t = call.prompt_text
    label = ""
    if site.prefix and t.startswith(site.prefix):
        t = t[len(site.prefix):]
        lines = [x for x in site.prefix.splitlines() if x.strip()]
        if lines and len(lines[-1]) <= 120 and not lines[-1].rstrip().endswith(("?", ".", "!")):
            label = lines[-1].strip()
    if site.suffix and t.endswith(site.suffix):
        t = t[: len(t) - len(site.suffix)]
    t = t.strip()
    if not t:
        return call.prompt_text.strip()[:MAX_STATE_CHARS]
    return (f"{label}\n{t}" if label else t)[:MAX_STATE_CHARS]


def _logged_label(call: RawCall, site: SiteAnalysis) -> str:
    """The logged answer, mapped onto the step's label set so fidelity compares like with like."""
    from .trace import BOOLS, answer_value

    raw = answer_value(call.output)
    low = raw.strip().lower()
    if site.kind == "noul":
        return BOOLS.get(low, low)
    if site.kind == "score":
        try:
            return str(int(float(raw)))
        except ValueError:
            return raw
    for opt in site.options:
        if opt.strip().lower() == low:
            return opt
    for opt in sorted(site.options, key=len, reverse=True):  # label mentioned inside a sentence
        if re.search(rf"(?<![\w-]){re.escape(opt.lower())}(?![\w-])", low):
            return opt
    return raw


def build(report: TraceReport, calls: list[RawCall], accept: dict[str, str], out_dir: Path,
          name: str = "Imported pipeline") -> dict[str, Any]:
    """`accept` maps site -> primitive (choice|score|noul) for the steps to move. Writes the harness dir."""
    by_site = {s.site: s for s in report.sites}
    unknown = [s for s in accept if s not in by_site]
    if unknown:
        raise ValueError(f"unknown step(s): {unknown}")
    sites: dict[str, Any] = {}
    for s in report.sites:
        kind = accept.get(s.site, "generation")
        if kind not in ("choice", "score", "noul", "generation"):
            raise ValueError(f"{s.site}: unknown primitive {kind!r}")
        if kind != "generation" and not s.overridable and not s.movable:
            raise ValueError(f"{s.site}: this step writes text ({s.med_out_tokens} output tokens); it cannot "
                             "be answered from a fixed menu")
        opts = s.options
        if kind in ("noul", "generation"):
            opts = {} if kind == "noul" else opts
        elif len(opts) < 2:
            raise ValueError(f"{s.site}: only {len(opts)} option(s) were found in the log, so there is no menu "
                             "to choose from. Keep it on the LLM, or log more calls for this step.")
        sites[s.site] = {"kind": kind, "options": opts, "instructions": s.instructions,
                         "max_tokens": max(32, min(512, s.med_out_tokens * 2 + 16)),
                         "primitive_note": s.reason}
    tasks: dict[str, dict[str, Any]] = {}
    for c in calls:
        s = by_site[c.site]
        t = tasks.setdefault(c.task_id, {"id": c.task_id, "steps": []})
        t["steps"].append({"site": c.site, "key": f"{c.site}#{len(t['steps'])}",
                           "messages": c.messages, "state": _state_of(c, s),
                           "logged": _logged_label(c, s), "logged_raw": c.output[:2000],
                           "prompt_tokens": c.prompt_tokens, "completion_tokens": c.completion_tokens,
                           "latency_ms": c.latency_ms})
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    moved = ", ".join(f"{k} -> {v}" for k, v in sorted(accept.items())) or "none"
    meta_sites = {s.site: (f"{sites[s.site]['kind']}: {s.reason}") for s in report.sites}
    meta = {"name": name, "imported": True,
            "description": f"Replayed from {Path(report.path).name or 'an imported call log'}: "
                           f"{report.n_calls} logged calls over {report.n_tasks} tasks, "
                           f"{len(accept)} of {len(report.sites)} steps moved to a decision model.",
            "sites": meta_sites, "imported_from": report.path, "moved": accept}
    # pformat, not json.dumps: this is Python source, so True/False/None must not become true/false/null.
    (out_dir / "harness.py").write_text(HARNESS.format(
        source=Path(report.path).name or "an imported call log", moved=moved,
        meta=pformat(meta, width=118, sort_dicts=False), sites=pformat(sites, width=118, sort_dicts=False)))
    with (out_dir / "tasks.jsonl").open("w") as f:
        for t in tasks.values():
            f.write(json.dumps(t, ensure_ascii=False) + "\n")
    (out_dir / "import.json").write_text(json.dumps(
        {"source": report.path, "accept": accept, "n_tasks": len(tasks), "n_calls": report.n_calls}, indent=2))
    return {"dir": str(out_dir), "harness": str(out_dir / "harness.py"), "tasks": str(out_dir / "tasks.jsonl"),
            "n_tasks": len(tasks), "moved": sorted(accept), "sites": sites}
