"""Build a runnable harness out of one or more single-trace run-tree exports (LangSmith/Langfuse/OTLP).

Unlike imported.build() (which replays a flat call log's exact logged prompts via legacy=), a run-tree
node's `inputs` aren't guaranteed to be a resendable chat prompt - each export format stores it
differently, and some don't store one at all. So this never tries to reproduce the original call. Every
agreed step asks the same distilled question (the instructions/options already reviewed on the Import
page) fresh, through whichever decider the arm uses: the main LLM by prompting for the baseline, a real
decision model for the candidate - exactly the same `ctx.decide.*` primitive imported.py's replay harness
uses, just without a `legacy=` to fall back on.

Only the agreed decision steps become part of the harness. Writing/generation steps aren't replayed -
nothing about them is being tested, and skipping them sidesteps the prompt-reconstruction problem above
entirely - so a task here is just "this trace's agreed decisions", not the full original pipeline.

One trace = one task. Loading several single-trace exports from the same agent is how this reaches more
than one task at all.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from pprint import pformat
from typing import Any

from .runtree import RunTree

HARNESS = '''"""Harness generated by JevControl from {n} single-trace export(s): {names}.

Do not hand-edit: rebuild it from the Import page instead.

Each task is one trace's agreed decision steps ({moved}). Every step asks the same question fresh: the
baseline arm answers by prompting the main LLM, a candidate arm by asking a decision model - neither
resends the export's own original prompt, since a run-tree node's real input isn't guaranteed to be one
across LangSmith/Langfuse/OTLP shapes (see jevcontrol/core/tree_import.py).

`score` compares the fresh answer to what the export originally recorded at that step, so it reads as
fidelity (does the decision reproduce what actually happened), not proven accuracy.
"""

META = {meta}

SITES = {sites}


def run(task, ctx):
    answers = {{}}
    for step in task["steps"]:
        site, key = step["site"], step["key"]
        spec = SITES[site]
        kind = spec["kind"]
        if kind == "noul":
            d = ctx.decide.noul(site, step["state"], spec["instructions"], key=key)
        elif kind == "score":
            d = ctx.decide.score(site, step["state"], spec["instructions"], spec["options"], key=key)
        else:
            d = ctx.decide.choice(site, step["state"], spec["instructions"], spec["options"], key=key)
        answers[key] = d.selected
    return answers


def score(task, out):
    """Fidelity: of this trace's agreed decisions, how many match what the export originally recorded."""
    graded = [(s["key"], s["logged"]) for s in task["steps"] if s.get("logged")]
    if not graded:
        return 1.0
    hit = sum(1 for key, logged in graded if str(out.get(key, "")).strip().lower() == str(logged).strip().lower())
    return hit / len(graded)
'''


def _logged_label(outputs: Any, kind: str, options: dict[str, str]) -> str:
    """A best-effort read of what the export recorded as this node's actual decision, mapped onto the
    step's label set: a plain string output, or a dict with a common key name, whichever is present."""
    raw = outputs
    if isinstance(outputs, dict):
        for key in ("decision", "answer", "selected", "output", "result", "value"):
            if key in outputs:
                raw = outputs[key]
                break
    raw = str(raw).strip()
    low = raw.lower()
    if kind == "noul":
        return {"true": "true", "yes": "true", "false": "false", "no": "false"}.get(low, low)
    for opt in options:
        if opt.strip().lower() == low:
            return opt
    for opt in sorted(options, key=len, reverse=True):
        if re.search(rf"(?<![\w-]){re.escape(opt.lower())}(?![\w-])", low):
            return opt
    return raw


def build(trees: list[RunTree], sites: dict[str, dict[str, Any]], out_dir: Path,
          name: str = "Trace-built pipeline") -> dict[str, Any]:
    """`sites` maps site name -> {kind, instructions, options} for the steps a person agreed to move -
    anything with kind="generation", or not listed at all, never becomes a harness step."""
    moved = {k: v for k, v in sites.items() if v.get("kind") in ("choice", "score", "noul")}
    if not moved:
        raise ValueError("no agreed decision steps to build a harness from")
    for site, spec in moved.items():
        if spec["kind"] != "noul" and len(spec.get("options") or {}) < 2:
            raise ValueError(f"{site}: fewer than 2 options - not a fixed menu")

    tasks: list[dict[str, Any]] = []
    for i, t in enumerate(trees):
        steps = []
        for n in t.nodes:
            spec = moved.get(n.name)
            if spec is None:
                continue
            steps.append({
                "site": n.name, "key": f"{n.name}#{len(steps)}",
                "state": n.inputs if n.inputs is not None else {},
                "logged": _logged_label(n.outputs, spec["kind"], spec.get("options") or {}),
            })
        if steps:
            tasks.append({"id": f"t{i:03d}", "steps": steps, "source": t.source})
    if not tasks:
        raise ValueError("none of the agreed steps were found in any of these traces")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    moved_txt = ", ".join(sorted(moved)) or "none"
    names = ", ".join(Path(t.source).name or "pasted" for t in trees)
    meta = {"name": name, "imported": True,
            "description": f"Built from {len(trees)} single-trace export(s): {len(moved)} agreed step(s) moved to a decision model.",
            "sites": {k: v["kind"] for k, v in moved.items()}, "moved": sorted(moved)}
    (out_dir / "harness.py").write_text(HARNESS.format(
        n=len(trees), names=names, moved=moved_txt,
        meta=pformat(meta, width=118, sort_dicts=False), sites=pformat(moved, width=118, sort_dicts=False)))
    with (out_dir / "tasks.jsonl").open("w") as f:
        for t in tasks:
            f.write(json.dumps(t, ensure_ascii=False, default=str) + "\n")
    return {"dir": str(out_dir), "harness": str(out_dir / "harness.py"), "tasks": str(out_dir / "tasks.jsonl"),
            "n_tasks": len(tasks), "moved": sorted(moved), "sites": moved}


def projection(trees: list[RunTree], sites: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """A rough before/after estimate for the summary card - one trace per step is too little to prove a
    saving; real numbers come from actually running the harness (see the callout in the UI)."""
    moved = {k for k, v in sites.items() if v.get("kind") in ("choice", "score", "noul")}
    calls = 0
    ptok = otok = 0
    for t in trees:
        for n in t.nodes:
            if n.name in moved:
                calls += 1
                ptok += n.prompt_tokens or 0
                otok += n.completion_tokens or 0
    n_tasks = max(1, len(trees))
    otok_after = calls  # a menu readout is one completion token per call
    before_tok, after_tok = ptok + otok, ptok + otok_after
    return {
        "n_tasks": len(trees), "accepted": sorted(moved),
        "llm_calls": {"before": calls / n_tasks, "after": 0.0},
        "decision_calls_after": calls / n_tasks,
        "llm_prompt_tokens": {"before": ptok, "after": ptok},
        "llm_output_tokens": {"before": otok, "after": otok_after},
        "llm_token_reduction": (1 - after_tok / before_tok) if before_tok else 0.0,
        "call_reduction": 1.0 if calls else 0.0,
        "cost_per_1k": {"before": 0.0, "after": 0.0}, "cost_reduction": None, "priced": False,
        "tokens_estimated": False, "llm_latency_removed_ms": 0.0, "llm_latency_total_ms": 0.0,
    }
